name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          CNAME: status.packit.dev
          GITHUB_ACTOR: jpopelka
          HUGO_VERSION: 0.80.0
          HUGO_EXTENDED: true
          TARGET_REPO: packit/status-github-pages
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.TOKEN }}
